apiVersion: v1
kind: Service
metadata:
  name: my-service-demo-nginx
  labels:
    name: my-service-demo-nginx
    app: my-service-app-demo-nginx
spec:
  type: LoadBalancer
  selector:
    name: my-pod-demo-nginx
  ports:
  -  port: 80
     targetPort: 80
     protocol: TCP
