apiVersion: v1
kind: Service
metadata:
  name: my-service-demo-nginx
  labels:
    name: my-service-demo-nginx
    app: my-service-app-demo-nginx
spec:
  template:
    metadata:
      name: my-pod-demo-nginx
      labels:
        name: my-pod-demo-nginx
        app: my-app-demo-nginx
    spec:
      containers:
        - name: my-container-nginx
          image: nginx
  selector:
    name: my-po-demo-nginx